// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package io.dapr

object DaprclientProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    com.google.protobuf.any.AnyProto,
    com.google.protobuf.empty.EmptyProto,
    com.google.protobuf.duration.DurationProto,
    io.dapr.DaprcommonProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      io.dapr.CloudEventEnvelope,
      io.dapr.BindingEventEnvelope,
      io.dapr.BindingResponseEnvelope,
      io.dapr.InvokeEnvelope,
      io.dapr.GetTopicSubscriptionsEnvelope,
      io.dapr.GetBindingsSubscriptionsEnvelope
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """ChBkYXByY2xpZW50LnByb3RvEgpkYXByY2xpZW50Ghlnb29nbGUvcHJvdG9idWYvYW55LnByb3RvGhtnb29nbGUvcHJvdG9id
  WYvZW1wdHkucHJvdG8aHmdvb2dsZS9wcm90b2J1Zi9kdXJhdGlvbi5wcm90bxoQZGFwcmNvbW1vbi5wcm90byK8AgoSQ2xvdWRFd
  mVudEVudmVsb3BlEhcKAmlkGAEgASgJQgfiPwQSAmlkUgJpZBIjCgZzb3VyY2UYAiABKAlCC+I/CBIGc291cmNlUgZzb3VyY2USH
  QoEdHlwZRgDIAEoCUIJ4j8GEgR0eXBlUgR0eXBlEjIKC3NwZWNWZXJzaW9uGAQgASgJQhDiPw0SC3NwZWNWZXJzaW9uUgtzcGVjV
  mVyc2lvbhI+Cg9kYXRhQ29udGVudFR5cGUYBSABKAlCFOI/ERIPZGF0YUNvbnRlbnRUeXBlUg9kYXRhQ29udGVudFR5cGUSIAoFd
  G9waWMYBiABKAlCCuI/BxIFdG9waWNSBXRvcGljEjMKBGRhdGEYByABKAsyFC5nb29nbGUucHJvdG9idWYuQW55QgniPwYSBGRhd
  GFSBGRhdGEimAIKFEJpbmRpbmdFdmVudEVudmVsb3BlEh0KBG5hbWUYASABKAlCCeI/BhIEbmFtZVIEbmFtZRIzCgRkYXRhGAIgA
  SgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueUIJ4j8GEgRkYXRhUgRkYXRhElkKCG1ldGFkYXRhGAMgAygLMi4uZGFwcmNsaWVudC5Ca
  W5kaW5nRXZlbnRFbnZlbG9wZS5NZXRhZGF0YUVudHJ5Qg3iPwoSCG1ldGFkYXRhUghtZXRhZGF0YRpRCg1NZXRhZGF0YUVudHJ5E
  hoKA2tleRgBIAEoCUII4j8FEgNrZXlSA2tleRIgCgV2YWx1ZRgCIAEoCUIK4j8HEgV2YWx1ZVIFdmFsdWU6AjgBIsUBChdCaW5ka
  W5nUmVzcG9uc2VFbnZlbG9wZRIzCgRkYXRhGAEgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueUIJ4j8GEgRkYXRhUgRkYXRhEhcKA
  nRvGAIgAygJQgfiPwQSAnRvUgJ0bxIoCgVzdGF0ZRgDIAMoCzIGLlN0YXRlQgriPwcSBXN0YXRlUgVzdGF0ZRIyCgtjb25jdXJyZ
  W5jeRgEIAEoCUIQ4j8NEgtjb25jdXJyZW5jeVILY29uY3VycmVuY3kikgIKDkludm9rZUVudmVsb3BlEiMKBm1ldGhvZBgBIAEoC
  UIL4j8IEgZtZXRob2RSBm1ldGhvZBIzCgRkYXRhGAIgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueUIJ4j8GEgRkYXRhUgRkYXRhE
  lMKCG1ldGFkYXRhGAMgAygLMiguZGFwcmNsaWVudC5JbnZva2VFbnZlbG9wZS5NZXRhZGF0YUVudHJ5Qg3iPwoSCG1ldGFkYXRhU
  ghtZXRhZGF0YRpRCg1NZXRhZGF0YUVudHJ5EhoKA2tleRgBIAEoCUII4j8FEgNrZXlSA2tleRIgCgV2YWx1ZRgCIAEoCUIK4j8HE
  gV2YWx1ZVIFdmFsdWU6AjgBIkQKHUdldFRvcGljU3Vic2NyaXB0aW9uc0VudmVsb3BlEiMKBnRvcGljcxgBIAMoCUIL4j8IEgZ0b
  3BpY3NSBnRvcGljcyJNCiBHZXRCaW5kaW5nc1N1YnNjcmlwdGlvbnNFbnZlbG9wZRIpCghiaW5kaW5ncxgBIAMoCUIN4j8KEghia
  W5kaW5nc1IIYmluZGluZ3MyswMKCkRhcHJDbGllbnQSPgoIT25JbnZva2USGi5kYXByY2xpZW50Lkludm9rZUVudmVsb3BlGhQuZ
  29vZ2xlLnByb3RvYnVmLkFueSIAElwKFUdldFRvcGljU3Vic2NyaXB0aW9ucxIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRopLmRhc
  HJjbGllbnQuR2V0VG9waWNTdWJzY3JpcHRpb25zRW52ZWxvcGUiABJiChhHZXRCaW5kaW5nc1N1YnNjcmlwdGlvbnMSFi5nb29nb
  GUucHJvdG9idWYuRW1wdHkaLC5kYXByY2xpZW50LkdldEJpbmRpbmdzU3Vic2NyaXB0aW9uc0VudmVsb3BlIgASWQoOT25CaW5ka
  W5nRXZlbnQSIC5kYXByY2xpZW50LkJpbmRpbmdFdmVudEVudmVsb3BlGiMuZGFwcmNsaWVudC5CaW5kaW5nUmVzcG9uc2VFbnZlb
  G9wZSIAEkgKDE9uVG9waWNFdmVudBIeLmRhcHJjbGllbnQuQ2xvdWRFdmVudEVudmVsb3BlGhYuZ29vZ2xlLnByb3RvYnVmLkVtc
  HR5IgBCGwoHaW8uZGFwckIQRGFwckNsaWVudFByb3Rvc2IGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
      com.google.protobuf.any.AnyProto.javaDescriptor,
      com.google.protobuf.empty.EmptyProto.javaDescriptor,
      com.google.protobuf.duration.DurationProto.javaDescriptor,
      io.dapr.DaprcommonProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}