// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package io.dapr

object DaprcommonProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    com.google.protobuf.any.AnyProto,
    com.google.protobuf.empty.EmptyProto,
    com.google.protobuf.duration.DurationProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      io.dapr.State,
      io.dapr.StateOptions,
      io.dapr.RetryPolicy
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """ChBkYXByY29tbW9uLnByb3RvGhlnb29nbGUvcHJvdG9idWYvYW55LnByb3RvGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvd
  G8aHmdvb2dsZS9wcm90b2J1Zi9kdXJhdGlvbi5wcm90byLFAgoFU3RhdGUSGgoDa2V5GAEgASgJQgjiPwUSA2tleVIDa2V5EjYKB
  XZhbHVlGAIgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueUIK4j8HEgV2YWx1ZVIFdmFsdWUSHQoEZXRhZxgDIAEoCUIJ4j8GEgRld
  GFnUgRldGFnEj8KCG1ldGFkYXRhGAQgAygLMhQuU3RhdGUuTWV0YWRhdGFFbnRyeUIN4j8KEghtZXRhZGF0YVIIbWV0YWRhdGESN
  QoHb3B0aW9ucxgFIAEoCzINLlN0YXRlT3B0aW9uc0IM4j8JEgdvcHRpb25zUgdvcHRpb25zGlEKDU1ldGFkYXRhRW50cnkSGgoDa
  2V5GAEgASgJQgjiPwUSA2tleVIDa2V5EiAKBXZhbHVlGAIgASgJQgriPwcSBXZhbHVlUgV2YWx1ZToCOAEiuAEKDFN0YXRlT3B0a
  W9ucxIyCgtjb25jdXJyZW5jeRgBIAEoCUIQ4j8NEgtjb25jdXJyZW5jeVILY29uY3VycmVuY3kSMgoLY29uc2lzdGVuY3kYAiABK
  AlCEOI/DRILY29uc2lzdGVuY3lSC2NvbnNpc3RlbmN5EkAKC3JldHJ5UG9saWN5GAMgASgLMgwuUmV0cnlQb2xpY3lCEOI/DRILc
  mV0cnlQb2xpY3lSC3JldHJ5UG9saWN5IqkBCgtSZXRyeVBvbGljeRIsCgl0aHJlc2hvbGQYASABKAVCDuI/CxIJdGhyZXNob2xkU
  gl0aHJlc2hvbGQSJgoHcGF0dGVybhgCIAEoCUIM4j8JEgdwYXR0ZXJuUgdwYXR0ZXJuEkQKCGludGVydmFsGAMgASgLMhkuZ29vZ
  2xlLnByb3RvYnVmLkR1cmF0aW9uQg3iPwoSCGludGVydmFsUghpbnRlcnZhbEIVCgdpby5kYXByQgpEYXByQ29tbW9uYgZwcm90b
  zM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
      com.google.protobuf.any.AnyProto.javaDescriptor,
      com.google.protobuf.empty.EmptyProto.javaDescriptor,
      com.google.protobuf.duration.DurationProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}