// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package io.dapr

object DaprProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    com.google.protobuf.any.AnyProto,
    com.google.protobuf.empty.EmptyProto,
    com.google.protobuf.duration.DurationProto,
    io.dapr.DaprcommonProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      io.dapr.InvokeServiceResponseEnvelope,
      io.dapr.DeleteStateEnvelope,
      io.dapr.SaveStateEnvelope,
      io.dapr.GetStateEnvelope,
      io.dapr.GetStateResponseEnvelope,
      io.dapr.InvokeBindingEnvelope,
      io.dapr.InvokeServiceEnvelope,
      io.dapr.PublishEventEnvelope,
      io.dapr.StateRequest,
      io.dapr.StateRequestOptions,
      io.dapr.StateRetryPolicy
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CgpkYXByLnByb3RvEgRkYXByGhlnb29nbGUvcHJvdG9idWYvYW55LnByb3RvGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvd
  G8aHmdvb2dsZS9wcm90b2J1Zi9kdXJhdGlvbi5wcm90bxoQZGFwcmNvbW1vbi5wcm90byKFAgodSW52b2tlU2VydmljZVJlc3Bvb
  nNlRW52ZWxvcGUSMwoEZGF0YRgBIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnlCCeI/BhIEZGF0YVIEZGF0YRJcCghtZXRhZGF0Y
  RgCIAMoCzIxLmRhcHIuSW52b2tlU2VydmljZVJlc3BvbnNlRW52ZWxvcGUuTWV0YWRhdGFFbnRyeUIN4j8KEghtZXRhZGF0YVIIb
  WV0YWRhdGEaUQoNTWV0YWRhdGFFbnRyeRIaCgNrZXkYASABKAlCCOI/BRIDa2V5UgNrZXkSIAoFdmFsdWUYAiABKAlCCuI/BxIFd
  mFsdWVSBXZhbHVlOgI4ASKHAQoTRGVsZXRlU3RhdGVFbnZlbG9wZRIaCgNrZXkYASABKAlCCOI/BRIDa2V5UgNrZXkSHQoEZXRhZ
  xgCIAEoCUIJ4j8GEgRldGFnUgRldGFnEjUKB29wdGlvbnMYAyABKAsyDS5TdGF0ZU9wdGlvbnNCDOI/CRIHb3B0aW9uc1IHb3B0a
  W9ucyJSChFTYXZlU3RhdGVFbnZlbG9wZRI9CghyZXF1ZXN0cxgBIAMoCzISLmRhcHIuU3RhdGVSZXF1ZXN0Qg3iPwoSCHJlcXVlc
  3RzUghyZXF1ZXN0cyJiChBHZXRTdGF0ZUVudmVsb3BlEhoKA2tleRgBIAEoCUII4j8FEgNrZXlSA2tleRIyCgtjb25zaXN0ZW5je
  RgCIAEoCUIQ4j8NEgtjb25zaXN0ZW5jeVILY29uc2lzdGVuY3kibgoYR2V0U3RhdGVSZXNwb25zZUVudmVsb3BlEjMKBGRhdGEYA
  SABKAsyFC5nb29nbGUucHJvdG9idWYuQW55QgniPwYSBGRhdGFSBGRhdGESHQoEZXRhZxgCIAEoCUIJ4j8GEgRldGFnUgRldGFnI
  pQCChVJbnZva2VCaW5kaW5nRW52ZWxvcGUSHQoEbmFtZRgBIAEoCUIJ4j8GEgRuYW1lUgRuYW1lEjMKBGRhdGEYAiABKAsyFC5nb
  29nbGUucHJvdG9idWYuQW55QgniPwYSBGRhdGFSBGRhdGESVAoIbWV0YWRhdGEYAyADKAsyKS5kYXByLkludm9rZUJpbmRpbmdFb
  nZlbG9wZS5NZXRhZGF0YUVudHJ5Qg3iPwoSCG1ldGFkYXRhUghtZXRhZGF0YRpRCg1NZXRhZGF0YUVudHJ5EhoKA2tleRgBIAEoC
  UII4j8FEgNrZXlSA2tleRIgCgV2YWx1ZRgCIAEoCUIK4j8HEgV2YWx1ZVIFdmFsdWU6AjgBIrMCChVJbnZva2VTZXJ2aWNlRW52Z
  WxvcGUSFwoCaWQYASABKAlCB+I/BBICaWRSAmlkEiMKBm1ldGhvZBgCIAEoCUIL4j8IEgZtZXRob2RSBm1ldGhvZBIzCgRkYXRhG
  AMgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueUIJ4j8GEgRkYXRhUgRkYXRhElQKCG1ldGFkYXRhGAQgAygLMikuZGFwci5JbnZva
  2VTZXJ2aWNlRW52ZWxvcGUuTWV0YWRhdGFFbnRyeUIN4j8KEghtZXRhZGF0YVIIbWV0YWRhdGEaUQoNTWV0YWRhdGFFbnRyeRIaC
  gNrZXkYASABKAlCCOI/BRIDa2V5UgNrZXkSIAoFdmFsdWUYAiABKAlCCuI/BxIFdmFsdWVSBXZhbHVlOgI4ASJtChRQdWJsaXNoR
  XZlbnRFbnZlbG9wZRIgCgV0b3BpYxgBIAEoCUIK4j8HEgV0b3BpY1IFdG9waWMSMwoEZGF0YRgCIAEoCzIULmdvb2dsZS5wcm90b
  2J1Zi5BbnlCCeI/BhIEZGF0YVIEZGF0YSLkAgoMU3RhdGVSZXF1ZXN0EhoKA2tleRgBIAEoCUII4j8FEgNrZXlSA2tleRI2CgV2Y
  Wx1ZRgCIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnlCCuI/BxIFdmFsdWVSBXZhbHVlEh0KBGV0YWcYAyABKAlCCeI/BhIEZXRhZ
  1IEZXRhZxJLCghtZXRhZGF0YRgEIAMoCzIgLmRhcHIuU3RhdGVSZXF1ZXN0Lk1ldGFkYXRhRW50cnlCDeI/ChIIbWV0YWRhdGFSC
  G1ldGFkYXRhEkEKB29wdGlvbnMYBSABKAsyGS5kYXByLlN0YXRlUmVxdWVzdE9wdGlvbnNCDOI/CRIHb3B0aW9uc1IHb3B0aW9uc
  xpRCg1NZXRhZGF0YUVudHJ5EhoKA2tleRgBIAEoCUII4j8FEgNrZXlSA2tleRIgCgV2YWx1ZRgCIAEoCUIK4j8HEgV2YWx1ZVIFd
  mFsdWU6AjgBIskBChNTdGF0ZVJlcXVlc3RPcHRpb25zEjIKC2NvbmN1cnJlbmN5GAEgASgJQhDiPw0SC2NvbmN1cnJlbmN5Ugtjb
  25jdXJyZW5jeRIyCgtjb25zaXN0ZW5jeRgCIAEoCUIQ4j8NEgtjb25zaXN0ZW5jeVILY29uc2lzdGVuY3kSSgoLcmV0cnlQb2xpY
  3kYAyABKAsyFi5kYXByLlN0YXRlUmV0cnlQb2xpY3lCEOI/DRILcmV0cnlQb2xpY3lSC3JldHJ5UG9saWN5Iq4BChBTdGF0ZVJld
  HJ5UG9saWN5EiwKCXRocmVzaG9sZBgBIAEoBUIO4j8LEgl0aHJlc2hvbGRSCXRocmVzaG9sZBImCgdwYXR0ZXJuGAIgASgJQgziP
  wkSB3BhdHRlcm5SB3BhdHRlcm4SRAoIaW50ZXJ2YWwYAyABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb25CDeI/ChIIaW50Z
  XJ2YWxSCGludGVydmFsMrMDCgREYXByEkQKDFB1Ymxpc2hFdmVudBIaLmRhcHIuUHVibGlzaEV2ZW50RW52ZWxvcGUaFi5nb29nb
  GUucHJvdG9idWYuRW1wdHkiABJTCg1JbnZva2VTZXJ2aWNlEhsuZGFwci5JbnZva2VTZXJ2aWNlRW52ZWxvcGUaIy5kYXByLklud
  m9rZVNlcnZpY2VSZXNwb25zZUVudmVsb3BlIgASRgoNSW52b2tlQmluZGluZxIbLmRhcHIuSW52b2tlQmluZGluZ0VudmVsb3BlG
  hYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IgASRAoIR2V0U3RhdGUSFi5kYXByLkdldFN0YXRlRW52ZWxvcGUaHi5kYXByLkdldFN0Y
  XRlUmVzcG9uc2VFbnZlbG9wZSIAEj4KCVNhdmVTdGF0ZRIXLmRhcHIuU2F2ZVN0YXRlRW52ZWxvcGUaFi5nb29nbGUucHJvdG9id
  WYuRW1wdHkiABJCCgtEZWxldGVTdGF0ZRIZLmRhcHIuRGVsZXRlU3RhdGVFbnZlbG9wZRoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0e
  SIAQigKB2lvLmRhcHJCCkRhcHJQcm90b3OqAhBEYXByLkNsaWVudC5HcnBjYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
      com.google.protobuf.any.AnyProto.javaDescriptor,
      com.google.protobuf.empty.EmptyProto.javaDescriptor,
      com.google.protobuf.duration.DurationProto.javaDescriptor,
      io.dapr.DaprcommonProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}